### ISSUE TITLE
api for fetching products data

### ISSUE THREAD

**Issue by Nitish-hack** [tamalCodes/Milan#700]
### Description

products displaying on shop page is static , API for fetching data from database and displaying it dynamically would be better

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Nitish-hack** [comment]
please assign this task to me

**Comment by IAmTamal** [comment]
Hi @Nitish-hack , great idea ⚡

Can you help me with these APIs before going for the `data fetching part` ? 

- Currently, we are fetching the shop's data statically from a [file](https://github.com/IAmTamal/Milan/blob/main/src/assets/data/shop/Shop_Data.js), and then just rendering it out based on categories
- You can understand this if you see the [Products.jsx](https://github.com/IAmTamal/Milan/blob/main/src/components/shop/Products.jsx) where we are filtering these data based on categories which are passed as params/props.
- I need you to make an API, so that I can add the  products to DB
- Then you can add an API to fetch the products !

Will you be able to do so ?

**Comment by Nitish-hack** [comment]
yeah I can do that, will that count as gssoc contribution?

**Comment by IAmTamal** [comment]
Hi @Nitish-hack Yes it will, you can make another issue for `Adding an API to fetch the products` and then start working on it. 

After than you can work on this issue - so you get 2 good contributions too !

**Comment by Nitish-hack** [comment]
awesome

**Comment by Nitish-hack** [comment]
should I put a new issue for "API to add products " so that you can assign me that

**Comment by IAmTamal** [comment]
> should I put a new issue for "API to add products " so that you can assign me that, as there is no assignees showing in this issue, you didn't assigned me i guess

![image](https://github.com/IAmTamal/Milan/assets/72851613/dcba3825-b77b-41ef-a9df-f0d416f6d88d)

**Comment by Nitish-hack** [comment]
okay

**Comment by Nitish-hack** [comment]
thanks
