### ISSUE TITLE
[FEATURE] Improve UX: Add default address message

### ISSUE THREAD

**Issue by Anmol-Baranwal** [tamalCodes/Milan#790]
### Description

As you can see from the screenshot, the address is shown as `na`, which is not good for user experience.

- To improve this, we can provide a default message that offers proper context.

> I would like to contribute to this issue under GSSoC'23.

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/74038190/0cfd92a2-d026-4174-9831-bab52a4d91cb)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @Anmol-Baranwal , that `na` does not means `not available` - it is the address the club gave while signing up. We have a moderation team that will remove such clubs with not good content/ change the content.

So I don't think we need a default address , because you cannot signup without providing address.

**Comment by Anmol-Baranwal** [comment]
> Hi @Anmol-Baranwal , that `na` does not means `not available` - it is the address the club gave while signing up. We have a moderation team that will remove such clubs with not good content/ change the content.
> 
> So I don't think we need a default address , because you cannot signup without providing address.

Thanks for letting me know.
