### ISSUE TITLE
[FEATURE] Add a scroll to top button on all pages

### ISSUE THREAD

**Issue by karthiknadar1204** [tamalCodes/Milan#908]
### Description

I was thinking of adding a scroll to top button on all the pages, I just saw that it is yet to be implemented on any page over the past two weeks, so though could give it a try .

For reference of my experience working with a similar issue, please refer issue #847 

I can get it done quickly

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by tamalCodes** [comment]
Hi @karthiknadar1204 , there is no concept of "getting it done quickly" in Opensource. I believe in your skills, but for now, I will put this issue on hold. Before moving on, I wait for at least 3-4 weeks and then I close an issue - in this case, I assigned them last week, so I will wait more - because contributors can be busy too, with 1000 different stuff.

We are not competing here for getting something done quickly, the goal is to give EVERYONE a chance, and to make sure there's a win-win scenario for everyone who is contributing to my project.

Anyways, putting this on-hold, this will be continued if #833 is discarded.

**Comment by karthiknadar1204** [comment]
Totally understandable,thank you so much ,will explore other issues to work with for time being.

**Comment by tamalCodes** [comment]
Hi @karthiknadar1204 , you can work and make a PR on this if interested, thanks !

### Remember, Good PR makes you a Good contributor !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits. Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.


- Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).

- Once you have done the changes you can `request` a review. If I suggest changes again, do those and `request` a review again.

- Make sure you DO NOT modify the PR template that we have, use it as it is.

- Last but not least, be patient. It takes a while to review the changes and get it merged.

**Comment by karthiknadar1204** [comment]
Thank you,will get working on it
