### ISSUE TITLE
[FEATURE] Want to Add Contributor page

### ISSUE THREAD

**Issue by biplavmz** [tamalCodes/Milan#992]
### Description

I want to add Contributor page so that people can see the contributors 

I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/tamalCodes/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)
- [X] I am a GSSoC23 contributor (blank for no).

**Comment by tamalCodes** [comment]
Hi there, thanks for raising this issue but unfortunately i will have to close this issue, because even if this is an amazing issue, we have like 135 contributors, so it makes no sense showing sooo many cards.

Plus anyonce can acess the contributors [here](https://github.com/tamalCodes/Milan/graphs/contributors)
